#!/usr/bin/python

import sys
import gtk
import gnomekeyring as gkey

class Keyring(object):
    def __init__(self, server, protocol):
        self._server = server
        self._protocol = protocol
        self._keyring = gkey.get_default_keyring_sync()

    def has_credentials(self):
        try:
            attrs = {"server": self._server, "protocol": self._protocol}
            items = gkey.find_items_sync(gkey.ITEM_NETWORK_PASSWORD, attrs)
            return len(items) > 0
        except gkey.DeniedError:
            return False

    def get_credentials(self):
        attrs = {"server": self._server, "protocol": self._protocol}
        items = gkey.find_items_sync(gkey.ITEM_NETWORK_PASSWORD, attrs)
        return (items[0].attributes["user"], items[0].secret)

    def set_credentials(self, (user, pw)):
        attrs = {
                "user": user,
                "server": self._server,
                "protocol": self._protocol,
            }
        gkey.item_create_sync(gkey.get_default_keyring_sync(),
              gkey.ITEM_NETWORK_PASSWORD, "%s://%s@%s" % (attrs["protocol"], attrs["user"], attrs["server"]), attrs, pw, True)

def get_username(server, protocol):
    keyring = Keyring(server, protocol)
    (username, password) = keyring.get_credentials()
    return username

def get_password(server, protocol):
    keyring = Keyring(server, protocol)
    (username, password) = keyring.get_credentials()
    return password

if __name__ == "__main__":
    import getpass
    proto = raw_input("Protocol: ")
    server = raw_input("Server: ")
    username = raw_input("Username: ")
    password = getpass.getpass(prompt="Password: ")
    print
    keyring = Keyring(server, proto)

    keyring.set_credentials((username, password))

