#!/bin/bash
# ls
#alias ls='ls -hF --color=auto --group-directories-first'
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

alias ls='ls++ -hF --group-directories-first'
alias ll='ls'
alias la='ls -A'
alias l='command ls -hF --color=auto --group-directories-first'


# ipython: awesome python interpreter
python() {
    if [ $# -eq 0 ]; then
        ipython
    else
        command python $@
    fi
}
alias uu='pkg u'
alias pacman='pacman-color'

# tools
alias up='cd ..'
alias home='cd ~'
alias lsgroup='cat /etc/group'
alias lsuser='cat /etc/passwd'
alias tracerout='tracepath'
alias spell='aspell -a <<< '
alias webshare='python2 -c "import SimpleHTTPServer; SimpleHTTPServer.test();"'
alias vim='vim -p'
alias vi='vi -p'
alias bc='bc -l'
alias rless='command less'
alias less='/usr/share/vim/vim73/macros/less.sh'
alias quit='exit'
alias :q='exit'
alias lsmail='~/.config/conky/mail.awk ~/.mail/**/new/*'

# Spelling
alias les='less'
alias pg='pkg'

# VPN
alias p="pgrep -lf"
calc(){ awk "BEGIN{ print $* }"}
alias calc="noglob calc"
alias service="sudo systemctl"

ranger() {
    command ranger --fail-unless-cd $@ &&
        cd "$(grep \^\' ~/.config/ranger/bookmarks | cut -b3-)" ||
        return 0
}

