#!/bin/bash
# ls
#alias ls='ls -hF --color=auto --group-directories-first'
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

alias ls='ls++ -hF --group-directories-first'
alias ll='ls'
alias la='ls -A'
alias l='command ls -hF --color=auto --group-directories-first'


# ipython: awesome python interpreter
python() {
    if [ $# -eq 0 ]; then
        ipython2
    else
        command python $@
    fi
}
alias uu='pkg u'
alias pacman='pacman-color'

# tools
alias up='cd ..'
alias home='cd ~'
alias lsgroup='cat /etc/group'
alias lsuser='cat /etc/passwd'
alias spell='aspell -a <<< '
alias webshare='python2 -c "import SimpleHTTPServer; SimpleHTTPServer.test();"'
alias vim='vim -p'
alias vi='vi -p'
alias bc='bc -l'
alias rless='command less'
alias less='/usr/share/vim/vim73/macros/less.sh'
alias quit='exit'
alias :q='exit'
alias lsmail='~/.config/conky/mail.awk ~/.mail/**/new/*'
alias curlpaste='curlpaste -X'
alias calc="wcalc"
alias p="pgrep -lf"
alias whois="whois -H"
alias walkman-sync="rsync --files-from=$XDG_DATA_HOME/mpd/playlists/best.m3u $HOME/Media/Music /media/WALKMAN/MUSIC; sync"

# Spelling
alias les='less'
alias pg='pkg'


alias owl='ssh -t linerva.mit.edu owl-tmux'

off() {
    if [[ -n "$DISPLAY" ]]; then
        xsession shutdown
    else
        dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop || sudo shutdown -h now
    fi
}

alias mit-sync='rsync -avz -e ssh ~/Documents/MIT/* MIT:~/Documents/'
