#!/bin/bash
# ls
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'

# ipython: awesome python interpreter
python() {
    if [ $# -eq 0 ]; then
        ipython
    else
        command python $@
    fi
}
alias uu='pkg u'
alias pacman='pacman-color'

# tools
alias up='cd ..'
alias home='cd ~'
alias lsgroup='cat /etc/group'
alias lsuser='cat /etc/passwd'
alias tracerout='tracepath'
alias spell='aspell -a <<< '
alias webshare='python -c "import SimpleHTTPServer; SimpleHTTPServer.test();"'
alias vim='vim -p'
alias vi='vi -p'
alias bc='bc -l'
alias rless='command less'
alias less='/usr/share/vim/vim73/macros/less.sh'
alias srm='srm -Dv'
alias quit='exit'
alias :q='exit'

# Spelling
alias les='less'
alias pg='pkg'

# VPN
vpn() {
    if [ -d /etc/openvpn/$1 ]; then
        cd /etc/openvpn/$1
        sudo openvpn client.conf
    else
        sudo openconnect --script /etc/vpnc/vpnc-script $1
    fi
}
alias p="pgrep -lf"
calc(){ awk "BEGIN{ print $* }"}
alias calc="noglob calc"
service() {
    serv=$1
    if test -x /etc/rc.d/$serv; then
        shift 1
        sudo /etc/rc.d/$serv $@
    else
        echo "Service \"$serv\" does not exist" >&2
    fi
}

ranger() {
    command ranger --fail-unless-cd $@ &&
        cd "$(grep \^\' ~/.config/ranger/bookmarks | cut -b3-)" ||
        return 0
}

