
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=* r:|=* l:|=*'

# Kill and killall
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*'   force-list always
zstyle ':completion:*:*:kill:*:processes' command 'ps haxopid:5,user:4,%cpu:4,ni:2,stat:3,etime:8,args'
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

zstyle ':completion:*:*:killall:*' menu yes select
zstyle ':completion:*:killall:*'   force-list always

# Disable correction in some commands
alias mv='nocorrect mv'
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'
alias pkg='nocorrect pkg'
alias man='nocorrect man'
alias git='nocorrect git'

# Disable globbing with find
alias find='noglob find'
alias pacman='noglob pacman'
alias pkg='noglob pkg'

zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit

# History
HISTFILE=$XDG_CONFIG_HOME/shell/history
HISTSIZE=1000
SAVEHIST=1000

# Random Options
setopt appendhistory autocd extendedglob interactivecomments cdablevars correctall incappendhistory histignorealldups histignorespace nobeep

# Key Bindings
bindkey -v
bindkey "\e[A" history-beginning-search-backward
bindkey "\e[B" history-beginning-search-forward
bindkey '^A' vi-beginning-of-line
bindkey '^E' vi-end-of-line
bindkey "^W" backward-kill-word    # vi-backward-kill-word
bindkey "^H" backward-delete-char  # vi-backward-delete-char
bindkey "^U" backward-kill-line    # vi-kill-line
bindkey "^?" backward-delete-char  # vi-backward-delete-char

bindkey -s '\er' "ranger\n"
bindkey -s '\e\e[A' "cd ..\n"
bindkey -s '\e\e[D' "cd -\n"
bindkey -s '\el' "ls\n"

bindkey '\e\e[B' clear-screen

# Remove sudo tty ticket on exit
zshexit() { sudo -n test -d /var/run/sudo/`whoami`/ 2> /dev/null && sudo -n rm /var/run/sudo/`whoami`/$(basename `tty`) }


# Source Global Functions
source $XDG_CONFIG_HOME/shell/functions

# Source anything for zsh (color functions etc)
for file in $XDG_CONFIG_HOME/shell/*.zsh; do
    source $file
done

# Vim as the pager
export PAGER='/bin/sh -c "unset PAGER;col -b -x | vim -u /usr/share/vim/vim73/macros/less.vim -R -c '\''set ft=man'\'' -c '\''nmap K :Man <C-R>=expand(\"<cword>\")<CR><CR>'\'' -c '\''set mouse=a'\'' -"'

# Source the header
source $XDG_CONFIG_HOME/shell/header
